server:
  port: 80

management:
  metrics:
    web:
      server:
        requests-metric-name: "application:request"
      client:
        requests-metric-name: "application:client_request"
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/status"
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    threaddump:
      enabled: true

  health:
    status:
      order: DOWN,OUT_OF_SERVICE,UNKNOWN,WARN,UP

spring:
  datasource:
    url: jdbc:postgresql://<set-db-endpoint>:5432/postgres
    username: postgres
    password: admin5432
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL81Dialect